name: phpunit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout on commit in the repository"
      uses: actions/checkout@v2
    - name: "Build the Docker image"
      run: docker build -t yapro/symfony-serializer-understanding:latest -f ./Dockerfile ./
    # run command in virtual machine
    - run: id
    - run: pwd
    - run: wget https://github.com/phpmd/phpmd/releases/download/2.12.0/phpmd.phar && chmod +x ./phpmd.phar
    - run: wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.8.0/php-cs-fixer.phar && chmod +x ./php-cs-fixer.phar
    # run commands in docker:
    - run: docker run --rm --user=$(id -u):$(id -g) -v $(pwd):/app -w /app yapro/symfony-serializer-understanding:latest ./phpmd.phar . text phpmd.xml --exclude .github/workflows,vendor --strict
    - run: docker run --rm --user=$(id -u):$(id -g) -v $(pwd):/app -w /app yapro/symfony-serializer-understanding:latest ./php-cs-fixer.phar fix --config=.php-cs-fixer.dist.php -v --dry-run --stop-on-violation --using-cache=no --allow-risky=yes --diff
    - run: docker run --rm --user=$(id -u):$(id -g) -v $(pwd):/app -w /app yapro/symfony-serializer-understanding:latest composer install --optimize-autoloader --no-scripts --no-interaction
    - run: docker run --rm --user=$(id -u):$(id -g) -v $(pwd):/app -w /app yapro/symfony-serializer-understanding:latest vendor/bin/phpunit --testsuite=Unit
